# -*- coding: utf-8 -*-
"""Blackjack Program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttUPhpif6mr55r34pjHBQUQeu1VAo5fA
"""

import random

# Create deck
def create_deck():
    deck = [2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 11] * 4
    random.shuffle(deck)
    return deck

# Calculate score
def calculate_score(hand):
  if sum(hand) == 21 and len(hand) == 2:
    return 0 # Blackjack

  if 11 in hand and sum(hand) > 21:
    hand[hand.index(11)] = 1

  return sum(hand)

# Deal card
def deal_card(deck):
  return deck.pop()

# Game logic
def play_game():
  deck = create_deck()
  player_hand = []
  dealer_hand = []

  for _ in range(2):
    player_hand.append(deal_card(deck))
    dealer_hand.append(deal_card(deck))

  game_over = False

  while not game_over:
    player_score = calculate_score(player_hand)
    dealer_score = calculate_score(dealer_hand)

    print(f"Your hand: {player_hand}, score: {player_score}")
    print(f"Dealer's first card: {dealer_hand[0]}")

    if player_score == 0 or player_score > 21:
      game_over = True
    else:
      choice = input("Type 'h' to hit or 's' to stand: ")
      if choice == 'h':
        player_hand.append(deal_card(deck))
      else:
        game_over = True
  while calculate_score(dealer_hand) < 17:
      dealer_hand.append(deal_card(deck))
  else:
      game_over = True

  print(f"\nFinal hands:")
  print(f"Your hand: {player_hand}, score: {calculate_score(player_hand)}")
  print(f"Dealer hand: {dealer_hand}, score: {calculate_score(dealer_hand)}")

# Determine winner
  player_score = calculate_score(player_hand)
  dealer_score = calculate_score(dealer_hand)

  if player_score > 21:
    print("You went over. You lose. 😢")
  elif dealer_score > 21:
    print("Dealer went over. You win! 😁")
  elif player_score == dealer_score:
    print("Draw 💙")
  elif player_score == 0:
    print("Blackjack! You win! 🖤")
  elif dealer_score == 0:
    print("Dealer has Blackjack. You lose. 😭")
  elif player_score > dealer_score:
    print("You win! 👍")
  else:
    print("You lose. 👎")

# Run game
while True:
  play = input("Do you want to play a game of Blackjack? Type 'y' or 'n': ")

  if play == 'y':
    play_game()
  elif play == 'n':
    print("Thanks for playing!")
    break

